"""add remark column

Revision ID: 10db7eac162b
Revises: 2c9b82b2ef1b
Create Date: 2026-06-25 17:21:11.378856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10db7eac162b'
down_revision: Union[str, Sequence[str], None] = '2c9b82b2ef1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_book', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_book', 'remark')
    # ### end Alembic commands ###
