"""add remark column new

Revision ID: dc88857f0edb
Revises: 10db7eac162b
Create Date: 2026-06-25 17:23:18.005614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc88857f0edb'
down_revision: Union[str, Sequence[str], None] = '10db7eac162b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_book', sa.Column('remark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_book', 'remark')
    # ### end Alembic commands ###
